sudo: required

services:
- docker

script:
- >
- docker build -t wise2c/kubeadm-version:$TRAVIS_BRANCH .
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- docker push wise2c/kubeadm-version:$TRAVIS_BRANCH
- docker run --rm --name=kubeadm-version wise2c/kubeadm-version:$TRAVIS_BRANCH kubeadm config images list
- docker run -d --name=kubeadm-config-migration --entrypoint=/bin/bash wise2c/kubeadm-version:$TRAVIS_BRANCH
- docker cp ./kubeadm.conf.old kubeadm-config-migration:/root/
- docker exec kubeadm-config-migration kubeadm config migrate --old-config /root/kubeadm.conf.old --new-config /root/kubeadm-config-new.yaml
- docker cp kubeadm-config-migration:/root/kubeadm-config-new.yaml ./
- cat ./kubeadm-config-new.yaml
