sudo: required
dist: focal

services:
- docker

before_install:
- mkdir -vp ~/.docker/cli-plugins/
- curl --silent -L "https://github.com/docker/buildx/releases/download/v0.4.2/buildx-v0.4.2.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
- chmod a+x ~/.docker/cli-plugins/docker-buildx
- docker buildx version

script:
- >
- docker buildx ls
- docker run --rm --privileged docker/binfmt:66f9012c56a8316f9244ffd7622d7c21c1f6f28d
- docker buildx create --use --name test > /dev/null
- docker buildx ls
- docker buildx build --platform linux/amd64,linux/arm64 -t wise2c/kubeadm-version:$TRAVIS_BRANCH .
#- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
#- docker push wise2c/kubeadm-version:$TRAVIS_BRANCH
#- docker run --rm --name=kubeadm-version wise2c/kubeadm-version:$TRAVIS_BRANCH kubeadm config images list
